name: Implantar na AWS
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - name: Fazer checkout do codigo
      #   uses: actions/checkout@v2
      - name: Debug AWS Credentials

      run: |
        echo "AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID"
        echo "AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY"
        aws configure list
  

      # - name: Configurar credenciais da AWS
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: us-east-2

      # - name: Implantar na AWS
      #   run: |
      #     aws s3 sync . s3://meuwebsite23     

          

